MercDevs_ej2/Controllers/RecepcionequipoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MercDevs_ej2.Models;
using Microsoft.CodeAnalysis;
using System;
using System.Security.Policy;

namespace MercDevs_ej2.Controllers
{
    public class RecepcionequipoesController : Controller
    {
        private readonly MercydevsEjercicio2Context _context;

        public RecepcionequipoesController(MercydevsEjercicio2Context context)
        {
            _context = context;
        }

        // GET: Recepcionequipoes
        public async Task<IActionResult> Index()
        {
            var mercydevsEjercicio2Context = _context.Recepcionequipos.Include(r => r.IdClienteNavigation).Include(r => r.IdServicioNavigation);
            return View(await mercydevsEjercicio2Context.ToListAsync());
        }


        public async Task<IActionResult> RecepcionPorId(int? id)
        {
            return View(await _context.Recepcionequipos.Where(u => u.IdCliente == id).ToListAsync());
        }


        // GET: Recepcionequipoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var recepcionequipo = await _context.Recepcionequipos
                .Include(r => r.IdClienteNavigation)
                .Include(r => r.IdServicioNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (recepcionequipo == null)
            {
                return NotFound();
            }

            return View(recepcionequipo);
        }

        // GET: Recepcionequipoes/Create
        public IActionResult Create()
        {
            ViewData["IdCliente"] = new SelectList(_context.Clientes, "IdCliente", "IdCliente");
            ViewData["IdServicio"] = new SelectList(_context.Servicios, "IdServicio", "IdServicio");
            return View();
        }

        // POST: Recepcionequipoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]





        public async Task<IActionResult> Create([Bind("Id,IdCliente,IdServicio,Fecha,TipoPc,Accesorio,MarcaPc,ModeloPc,Nserie,CapacidadRam,TipoAlmacenamiento,CapacidadAlmacenamiento,TipoGpu,Grafico, Estado")] Recepcionequipo recepcionequipo)
        {
            // primero quise hacer un if para validar los dato propios de la tabla, pero era muy largo
            //le pregunte a gpt-san como podia factorizar mejor el codigo y me explico que podia hacer un diccionario y recorrerlo
            //con el foreach se hizo rapido, entendi bastante con esto, puedo hacer filtros generales con el if y 
            //aplicarlo a un monton de datos usando diccionarios y foreach, esto acomoda mucho las cosas ojito O.O

            var tablaDato = new Dictionary<string, object?>
            //llamo al nombre del valor que quiero atribuir, y luego llamo al mismo valor, asi lo asigno a mi diccionario
    {
        { nameof(recepcionequipo.MarcaPc), recepcionequipo.MarcaPc  },
        { nameof(recepcionequipo.Fecha), recepcionequipo.Fecha },
        { nameof(recepcionequipo.TipoPc), recepcionequipo.TipoPc },
        { nameof(recepcionequipo.Accesorio), recepcionequipo.Accesorio },
        { nameof(recepcionequipo.ModeloPc), recepcionequipo.ModeloPc },
        { nameof(recepcionequipo.Nserie), recepcionequipo.Nserie },
        { nameof(recepcionequipo.CapacidadRam), recepcionequipo.CapacidadRam },
        { nameof(recepcionequipo.TipoAlmacenamiento), recepcionequipo.TipoAlmacenamiento },
        { nameof(recepcionequipo.CapacidadAlmacenamiento), recepcionequipo.CapacidadAlmacenamiento },
        { nameof(recepcionequipo.TipoGpu), recepcionequipo.TipoGpu },
        { nameof(recepcionequipo.Grafico), recepcionequipo.Grafico },
        { nameof(recepcionequipo.Estado), recepcionequipo.Estado }
    };

            // Verificar si alguna de las propiedades es nula o en el caso de int, si es igual a 0
            //quiero ver tambien si puedo validar una fecha, eso sera interesante :}
            //o quiza lo mejor sea agregar la fecha desde el sistema del pc, seria lo mas acertado 
            foreach (var dato in tablaDato)
            {
                if (dato.Value == null)
                {
                    // Si cualquier valor no cumple con los requisitos, se configura ViewData y se retorna la vista
                    ViewData["IdCliente"] = new SelectList(_context.Clientes, "IdCliente", "IdCliente", recepcionequipo.IdCliente);
                    ViewData["IdServicio"] = new SelectList(_context.Servicios, "IdServicio", "IdServicio", recepcionequipo.IdServicio);
                    return View(recepcionequipo);
                }
            }

            // Si todas las propiedades cumplen con los requisitos, se guarda en la base de datos
            _context.Add(recepcionequipo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }





        // GET: Recepcionequipoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var recepcionequipo = await _context.Recepcionequipos.FindAsync(id);
            if (recepcionequipo == null)
            {
                return NotFound();
            }
            ViewData["IdCliente"] = new SelectList(_context.Clientes, "IdCliente", "IdCliente", recepcionequipo.IdCliente);
            ViewData["IdServicio"] = new SelectList(_context.Servicios, "IdServicio", "IdServicio", recepcionequipo.IdServicio);
            return View(recepcionequipo);
        }

        // POST: Recepcionequipoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,IdCliente,IdServicio,Fecha,TipoPc,Accesorio,MarcaPc,ModeloPc," +
"Nserie,CapacidadRam,TipoAlmacenamiento,CapacidadAlmacenamiento,TipoGpu,Grafico,Estado")] Recepcionequipo recepcionequipo)
        {
            if (id != recepcionequipo.Id)
            {
                return NotFound();
            }

            if (recepcionequipo.IdCliente != 0) // Verificar si el modelo es válido
            {
                try
                {
                    _context.Update(recepcionequipo);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RecepcionequipoExists(recepcionequipo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "No se pudieron guardar los cambios. El registro fue actualizado o eliminado por otro usuario.");
                    }
                }
                catch (Exception ex)
                {
                    // Imprimir el mensaje de error en la consola
                    Console.WriteLine($"Error al guardar en la base de datos: {ex.Message}");

                    // También puedes imprimir detalles adicionales si los necesitas
                    Console.WriteLine($"Detalles adicionales: {ex.InnerException}");

                    ModelState.AddModelError(string.Empty, $"Ocurrió un error: {ex.Message}");
                }
            }

            // Si el modelo no es válido o si ocurre un error, vuelve a cargar los datos necesarios para mostrar la vista de edición
            ViewData["IdCliente"] = new SelectList(_context.Clientes, "IdCliente", "IdCliente", recepcionequipo.IdCliente);
            ViewData["IdServicio"] = new SelectList(_context.Servicios, "IdServicio", "IdServicio", recepcionequipo.IdServicio);
            return View(recepcionequipo);
        }


        private bool RecepcionequipoExists(int id)
        {
            return _context.Recepcionequipos.Any(e => e.Id == id);
        }






        // GET: Recepcionequipoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var recepcionequipo = await _context.Recepcionequipos
                .Include(r => r.IdClienteNavigation)
                .Include(r => r.IdServicioNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (recepcionequipo == null)
            {
                return NotFound();
            }

            return View(recepcionequipo);
        }

        // POST: Recepcionequipoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var recepcionequipo = await _context.Recepcionequipos.FindAsync(id);
            if (recepcionequipo != null)
            {
                _context.Recepcionequipos.Remove(recepcionequipo);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult>NewEstado(int? id )
        {
            if (id == null)
            {
                return NotFound();
            }

            var recepcionequipo = await _context.Recepcionequipos

                .FirstOrDefaultAsync(m => m.Id == id);
            if (recepcionequipo == null)
            {
                return NotFound();
            }

MercDevs_ej2/Views/Recepcionequipoes/Create.cshtml
@model MercDevs_ej2.Models.Recepcionequipo

@{
    ViewData["Title"] = "Create";
}

<h1>Crear Recepcion de Equipo</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdCliente" class="control-label"> Id del Cliente</label>
                <select asp-for="IdCliente" class ="form-control" asp-items="ViewBag.IdCliente"></select>
            </div>
            <div class="form-group">
                <label asp-for="IdServicio" class="control-label"> Id del Servicio</label>
                <select asp-for="IdServicio" class ="form-control" asp-items="ViewBag.IdServicio"></select>
            </div>
            <div class="form-group">
                <label asp-for="Fecha" class="control-label"></label>
                <input asp-for="Fecha" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoPc" class="control-label">Ingrese el tipo de pc</label>
                <input asp-for="TipoPc" class="form-control" />
                <span asp-validation-for="TipoPc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Accesorio" class="control-label">Accesorios</label>
                <input asp-for="Accesorio" class="form-control" />
                <span asp-validation-for="Accesorio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MarcaPc" class="control-label">marca del Pc</label>
                <input asp-for="MarcaPc" class="form-control" />
                <span asp-validation-for="MarcaPc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModeloPc" class="control-label">el Modelo del pc</label>
                <input asp-for="ModeloPc" class="form-control" />
                <span asp-validation-for="ModeloPc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nserie" class="control-label"> N° Serie del Pc</label>
                <input asp-for="Nserie" class="form-control" />
                <span asp-validation-for="Nserie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CapacidadRam" class="control-label">Capacidad de Ram</label>
                <input asp-for="CapacidadRam" class="form-control" />
                <span asp-validation-for="CapacidadRam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoAlmacenamiento" class="control-label">Tipo de almacenamieto</label>
                <input asp-for="TipoAlmacenamiento" class="form-control" />
                <span asp-validation-for="TipoAlmacenamiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CapacidadAlmacenamiento" class="control-label">Capacidad de Almacenamiento</label>
                <input asp-for="CapacidadAlmacenamiento" class="form-control" />
                <span asp-validation-for="CapacidadAlmacenamiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoGpu" class="control-label">Tipo de Gpu</label>
                <input asp-for="TipoGpu" class="form-control" />
                <span asp-validation-for="TipoGpu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Grafico" class="control-label">Graficos</label>
                <input asp-for="Grafico" class="form-control" />
                <span asp-validation-for="Grafico" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label">Estado</label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="crear Recepcion" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index"><button class="btn btn-secondary">Volver a la lista</button></a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MercDevs_ej2/Views/Recepcionequipoes/Delete.cshtml
@model MercDevs_ej2.Models.Recepcionequipo

@{
    ViewData["Title"] = "Delete";
}

<h1>Borrar Recepcion de equipo</h1>

<h3>¿estas seguro de que quieres eliminar esto?</h3>
<div>

    <hr />
    <dl class="row ">
        <dt class="col-sm-2">
            Fecha:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <hr style="background-color:black" />
        <dt class="col-sm-2">
            Tipo de PC
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TipoPc)
        </dd>
        <hr style="background-color:black" />

        <dt class="col-sm-2">
            AccesoriosS
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Accesorio)
        </dd>
        <hr style="background-color:black" />


        <dt class="col-sm-2">
            Marca de Pc
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MarcaPc)
        </dd>
        <hr style="background-color:black" />


        <dt class="col-sm-2">
            modelo de Pc
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ModeloPc)
        </dd>
        <hr style="background-color:black" />


        <dt class="col-sm-2">
            N° Serie
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nserie)
        </dd>
        <hr style="background-color:black" />


        <dt class="col-sm-2">
            Capacidad de Ram
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CapacidadRam)
        </dd>
        <hr style="background-color:black" />


        <dt class="col-sm-2">
            Tipo almacenamiento
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TipoAlmacenamiento)
        </dd>
        <hr style="background-color:black" />


        <dt class="col-sm-2">
            Cap Almacenamiento
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CapacidadAlmacenamiento)
        </dd>
        <hr style="background-color:black" />


        <dt class="col-sm-2">
            Tipo Gpu
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TipoGpu)
        </dd>
        <hr style="background-color:black" />


        <dt class="col-sm-2">
            Graficos
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Grafico)
        </dd>
        <hr style="background-color:black" />


        <dt class="col-sm-2">
            Id cliente
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdClienteNavigation.IdCliente)
        </dd>
        <hr style="background-color:black" />


        <dt class="col-sm-2">
            Id servicio
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdServicioNavigation.IdServicio)
        </dd>
        <hr style="background-color:black" />


    </dl>
</div>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Borrar" class="btn btn-danger" /> 
        <a asp-action="Index"><button class="btn btn-secondary">volver a la lista</button></a>
    </form>
</div>

MercDevs_ej2/Views/Recepcionequipoes/Details.cshtml
@model MercDevs_ej2.Models.Recepcionequipo

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles de recepcion</h1>

<div>

    <hr />
    <dl class="row ">
        <dt class = "col-sm-2">
            Fecha:
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <hr style="background-color:black"/>
        <dt class = "col-sm-2">
            Tipo de PC
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoPc)
        </dd>
        <hr style="background-color:black" />

        <dt class = "col-sm-2">
           AccesoriosS
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Accesorio)
        </dd>
        <hr style="background-color:black" />


        <dt class = "col-sm-2">
            Marca de Pc
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MarcaPc)
        </dd>
        <hr style="background-color:black" />


        <dt class = "col-sm-2">
            modelo de Pc
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModeloPc)
        </dd>
        <hr style="background-color:black" />


        <dt class = "col-sm-2">
            N° Serie
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nserie)
        </dd>
        <hr style="background-color:black" />


        <dt class = "col-sm-2">
            Capacidad de Ram
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CapacidadRam)
        </dd>
        <hr style="background-color:black" />


        <dt class = "col-sm-2">
            Tipo almacenamiento
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoAlmacenamiento)
        </dd>
        <hr style="background-color:black" />


        <dt class = "col-sm-2">
            Cap Almacenamiento
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CapacidadAlmacenamiento)
        </dd>
        <hr style="background-color:black" />


        <dt class = "col-sm-2">
            Tipo Gpu
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoGpu)
        </dd>
        <hr style="background-color:black" />


        <dt class = "col-sm-2">
            Graficos
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Grafico)
        </dd>
        <hr style="background-color:black" />


        <dt class = "col-sm-2">
            Id cliente
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdClienteNavigation.IdCliente)
        </dd>
        <hr style="background-color:black"/>


        <dt class = "col-sm-2">
            Id servicio
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdServicioNavigation.IdServicio)
        </dd>
        <hr style="background-color:black" />


    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id"><button class="btn btn-warning">editar</button></a>
    <a asp-action="Index"><button class="btn btn-secondary">volver a listado</button></a>
</div>

MercDevs_ej2/Views/Recepcionequipoes/Edit.cshtml
@model MercDevs_ej2.Models.Recepcionequipo

@{
    ViewData["Title"] = "Editar Recepción";
}

<h1>Editar Recepción</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <label asp-for="IdCliente" class="control-label">Id Cliente</label>
                <select asp-for="IdCliente" class="form-control" asp-items="ViewBag.IdCliente"></select>
                <span asp-validation-for="IdCliente" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="IdServicio" class="control-label">Id Servicio</label>
                <select asp-for="IdServicio" class="form-control" asp-items="ViewBag.IdServicio"></select>
                <span asp-validation-for="IdServicio" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Fecha" class="control-label">Fecha</label>
                <input asp-for="Fecha" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="TipoPc" class="control-label">Tipo PC</label>
                <input asp-for="TipoPc" class="form-control" />
                <span asp-validation-for="TipoPc" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Accesorio" class="control-label">Accesorios</label>
                <input asp-for="Accesorio" class="form-control" />
                <span asp-validation-for="Accesorio" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="MarcaPc" class="control-label">Marca PC</label>
                <input asp-for="MarcaPc" class="form-control" />
                <span asp-validation-for="MarcaPc" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ModeloPc" class="control-label">Modelo PC</label>
                <input asp-for="ModeloPc" class="form-control" />
                <span asp-validation-for="ModeloPc" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Nserie" class="control-label">N° Serie</label>
                <input asp-for="Nserie" class="form-control" />
                <span asp-validation-for="Nserie" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CapacidadRam" class="control-label">Capacidad de RAM</label>
                <input asp-for="CapacidadRam" class="form-control" />
                <span asp-validation-for="CapacidadRam" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="TipoAlmacenamiento" class="control-label">Tipo de Almacenamiento</label>
                <input asp-for="TipoAlmacenamiento" class="form-control" />
                <span asp-validation-for="TipoAlmacenamiento" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CapacidadAlmacenamiento" class="control-label">Capacidad de Almacenamiento</label>
                <input asp-for="CapacidadAlmacenamiento" class="form-control" />
                <span asp-validation-for="CapacidadAlmacenamiento" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="TipoGpu" class="control-label">Tipo de GPU</label>
                <input asp-for="TipoGpu" class="form-control" />
                <span asp-validation-for="TipoGpu" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Grafico" class="control-label">Gráfico</label>
                <input asp-for="Grafico" class="form-control" />
                <span asp-validation-for="Grafico" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-warning" />
            </div>
        </form>
    </div>
</div>

    <div>
        <a asp-action="Index" class="btn btn-secondary">Volver a la lista</a>
    </div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MercDevs_ej2/Views/Recepcionequipoes/Index.cshtml
@model IEnumerable<MercDevs_ej2.Models.Recepcionequipo>

@{
    ViewData["Title"] = "Index";
}

<h1>Index Recepcion De equipos</h1>
<body style="align-content:center">
<p>
        <a asp-action="Create"><button type="button" class="btn btn-success ">Crear Recepcion</button></a>
</p>
<table class="table">
    <thead td style="white-space: nowrap;">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Fecha)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoPc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Accesorio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MarcaPc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModeloPc)
            </th>
            <th>
                N° Serie
            </th>
            <th>
                Cap Ram
            </th>
            <th>
                Tipo almacenamiento
            </th>
            <th>
                Cap Almacenamiento
            </th>
            <th>
                Tipo_Gpu
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Grafico)
            </th>
            <th>Estado</th>
            <th>
               Id Cliente
            </th>
            <th>
                Id servicio    
            </th>

            <th>Acciones</th>
        </tr>
    </thead>
    <tbody style="text-align">
@foreach (var item in Model) {
        <tr>
            <td style="white-space: nowrap;">
                @Html.DisplayFor(modelItem => item.Fecha)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoPc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Accesorio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MarcaPc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ModeloPc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nserie)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CapacidadRam)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoAlmacenamiento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CapacidadAlmacenamiento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoGpu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Grafico)
            </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Estado)
                    </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdClienteNavigation.IdCliente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdServicioNavigation.IdServicio)
            </td>
            <td>

                <div class="d-flex justify-content-around" style="gap:10px">
                    <a asp-action="Edit" asp-route-id="@item.Id">
                        <button type="button" class="btn btn-primary" style="width:100%">Editar</button></a>

                    <a asp-action="Details" asp-route-id="@item.Id">
                        <button type="button" class="btn btn-info" style="width:100%">Detalles</button></a> 

                    <a asp-action="Delete" asp-route-id="@item.Id">
                            <button type="button" class="btn btn-danger" style="width:100%">Borrar</button>
                        </a>
                            @if (item.Estado != 0)
                            {
                                <a asp-route-id="@item.Id" asp-action="NewEstado" asp-controller="Recepcionequipoes">
                                    <button class="btn btn-warning">Estado completado</button>

                                </a>
                            }

                    </div>
            </td>
        </tr>
}
    </tbody>
</table>
</body>

MercDevs_ej2/Views/Recepcionequipoes/NewEstado.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model MercDevs_ej2.Models.Recepcionequipo

@{
    ViewData["Title"] = "Delete";
}

<h1>Cambiar estado a completado</h1>

<h3>¿estas seguro de que quieres actualizar el estado?</h3>
<div>


    </dl>
</div>

<form asp-action="">
    <input type="hidden" asp-for="Id" />
    <input type="submit" value="actualizar" class="btn btn-danger" />
    <a asp-action="Index"><button class="btn btn-secondary">volver a la lista</button></a>
</form>
</div>